### PR TITLE
changed emojis to text in buttons

### PR DESCRIPTION
**Pull request by Reyuu**
Emojis were causing display problems. Replaced them with text.

### CODE REVIEW

**Comment by krassowski** [comment]
What kind of problem where they causing?

**Comment by Reyuu** [comment]
@krassowski They weren't displaying correctly
image

Text would be the best, platform agnostic option in this case imo, which is why I suggested this PR.

**Comment by krassowski** [comment]
Looks like a font-size issue and I think it should be fixed by setting the font size on the glyphs. I appreciate your effort but I am sure that there would be users who will consider the larger buttons with text rather than icons to be a step backwards; also, not everyone is speaking English and ideally, you should also provide translations to all the languages that Anki support (the add-on being documented in English does not mean that the basic functionality is not used by non-English speakers).

**Comment by Reyuu** [comment]
Ah I somehow missed it in my reasoning. Sorry about it.

Let's close this PR then.

**Pull request closed without merging**
